
import type { Metadata } from 'next'
import DevelopersGuideHeader from './components/header'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: {children: React.ReactNode
}) {
  return (
    <div className='w-full max-w-screen-2xl mx-auto items-center bg-zinc-100 h-[100vh]'>
      
        <DevelopersGuideHeader />
        
        {children}
    </div>
  )
}
