
import type { Metadata } from 'next'
import DevelopersGuideHeader from './components/header'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function DevelopersGuideCorpLayout({children,}: {children: React.ReactNode
}) {
  return (
    <div className='w-full  mx-auto items-center bg-zinc-100 '>
      
        <DevelopersGuideHeader />
        
        {children}
    </div>
  )
}
